version: "1.0"
services:
  web:
    image: registry.gitlab-forge.din.developpement-durable.gouv.fr/pub/dnumarchi/welcome-page/welcome-page
    ports:
      - "${WELCOME_PORT}:80"
    environment:
      - WELCOME_TITRE="${WELCOME_TITRE}"
